# How ou

In [1]:
import pandas as pd
import seaborn as sns

## 2 - Data Loading and Overview

Understand how the dataset is structured and how the data behaves in order to start making informed feature engineering decisions

In [2]:
df = pd.read_csv('2019-Nov.csv')

In [3]:
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:00:00 UTC,view,1003461,2053013555631882655,electronics.smartphone,xiaomi,489.07,520088904,4d3b30da-a5e4-49df-b1a8-ba5943f1dd33
1,2019-11-01 00:00:00 UTC,view,5000088,2053013566100866035,appliances.sewing_machine,janome,293.65,530496790,8e5f4f83-366c-4f70-860e-ca7417414283
2,2019-11-01 00:00:01 UTC,view,17302664,2053013553853497655,NaN,creed,28.31,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
3,2019-11-01 00:00:01 UTC,view,3601530,2053013563810775923,appliances.kitchen.washer,lg,712.87,518085591,3bfb58cd-7892-48cc-8020-2f17e6de6e7f
4,2019-11-01 00:00:01 UTC,view,1004775,2053013555631882655,electronics.smartphone,xiaomi,183.27,558856683,313628f1-68b8-460d-84f6-cec7a8796ef2

In [4]:
df.describe()

         product_id   category_id         price       user_id
count  6.750198e+07  6.750198e+07  6.750198e+07  6.750198e+07
mean   1.251406e+07  2.057898e+18  2.924593e+02  5.386397e+08
std    1.725741e+07  2.012549e+16  3.556745e+02  2.288516e+07
min    1.000365e+06  2.053014e+18  0.000000e+00  1.030022e+07
25%    1.305977e+06  2.053014e+18  6.924000e+01  5.164762e+08
50%    5.100568e+06  2.053014e+18  1.657700e+02  5.350573e+08
75%    1.730075e+07  2.053014e+18  3.603400e+02  5.610794e+08
max    1.000286e+08  2.187708e+18  2.574070e+03  5.799699e+08

In [ ]:
df['event_type'].unique()

array(['view', 'cart', 'purchase'], dtype=object)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67501979 entries, 0 to 67501978
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     object
 1   event_type     object
 2   product_id     int64
 3   category_id    int64
 4   category_code  object
 5   brand          object
 6   price          float64
 7   user_id        int64
 8   user_session   object
dtypes: float64(1), int64(3), object(5)
memory usage: 4.5+ GB

In [9]:
df.isnull().sum()

event_time              0
event_type              0
product_id              0
category_id             0
category_code    21898171
brand             9224078
price                   0
user_id                 0
user_session           10
dtype: int64