# E-Commerce User Behavior Analysis

his project explores user behavior in a real-world e-commerce dataset containing over 5 million user interactions. The goal is to analyze the customer journey and uncover patterns that drive conversions — from product views to cart additions and final purchases.

Throughout the analysis, I:
- Clean and preprocess the raw dataset (5GB CSV) to ensure consistency and accuracy
- Perform exploratory data analysis (EDA) to identify trends across time, categories, brands, and prices
- Build a complete **conversion funnel**: `view → cart → purchase`
- Uncover the most profitable time slots and product categories
- Visualize key insights to support decision-making in e-commerce strategies

This project emphasizes real-world data wrangling, storytelling through visualizations, and performance-aware analysis at scale using Python and Pandas.

In [1]:
import pandas as pd
import seaborn as sns

## 1. Data Loading and Overview

Understand how the dataset is structured and how the data behaves in order to start making informed feature engineering decisions

In [ ]:
# df = pd.read_csv('data/2019-Nov.csv')
df = pd.read_csv('data/ecommerce_sample.csv')

In [12]:
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-15 06:07:59 UTC,view,11800010,2053013561243861733,NaN,NaN,3.86,549469656,a16e52ec-6b97-4933-ab53-f43c49f72406
1,2019-11-19 06:35:02 UTC,view,5100660,2053013553341792533,electronics.clocks,suunto,514.56,521310840,65f324a6-d63d-4a4e-9300-7b88a4596ebf
2,2019-11-15 06:03:37 UTC,cart,1005130,2053013555631882655,electronics.smartphone,apple,1523.76,556014234,516ad743-d468-496b-b714-2ce4bdc37896
3,2019-11-10 18:49:19 UTC,cart,1307188,2053013558920217191,computers.notebook,hp,223.92,567469797,abd50ea6-35d7-40bb-a9fc-cc8e5f2fd1e3
4,2019-11-05 17:45:54 UTC,view,1004833,2053013555631882655,electronics.smartphone,samsung,170.05,567450890,6c2bf03d-2aa2-4389-ac23-613979976c7d

In [13]:
df.describe()

         product_id   category_id          price       user_id
count  1.000000e+05  1.000000e+05  100000.000000  1.000000e+05
mean   1.247455e+07  2.057854e+18     292.485454  5.385883e+08
std    1.721470e+07  2.005989e+16     355.178646  2.276398e+07
min    1.000978e+06  2.053014e+18       0.000000  1.567075e+08
25%    1.306021e+06  2.053014e+18      69.180000  5.164727e+08
50%    5.100562e+06  2.053014e+18     166.230000  5.349188e+08
75%    1.730075e+07  2.053014e+18     361.320000  5.609055e+08
max    1.000285e+08  2.187708e+18    2574.070000  5.799592e+08

In [14]:
df['event_type'].unique()

array(['view', 'cart', 'purchase'], dtype=object)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   event_time     100000 non-null  object
 1   event_type     100000 non-null  object
 2   product_id     100000 non-null  int64
 3   category_id    100000 non-null  int64
 4   category_code  67644 non-null   object
 5   brand          86679 non-null   object
 6   price          100000 non-null  float64
 7   user_id        100000 non-null  int64
 8   user_session   100000 non-null  object
dtypes: float64(1), int64(3), object(5)
memory usage: 6.9+ MB

In [24]:
df.isnull().sum()

event_time       0
event_type       0
product_id       0
category_id      0
category_code    0
brand            0
price            0
user_id          0
user_session     0
dtype: int64

In [26]:
df.duplicated().sum()

100519

## 2. Data Cleaning and Preparation

In [22]:
df['category_code'].fillna('unknown', inplace=True)
df['brand'].fillna('unknown', inplace=True)

In [23]:
df.dropna(subset=['user_session'], inplace=True)

In [25]:
df.isnull().sum()

event_time       0
event_type       0
product_id       0
category_id      0
category_code    0
brand            0
price            0
user_id          0
user_session     0
dtype: int64

In [27]:
df.drop_duplicates(inplace=True)

In [28]:
df.duplicated().sum()

0